import { useEffect, useState } from 'react';
import { reportsApi, scansApi } from '../services/api';
import type { Report, Scan } from '../services/apiTypes';
import { FileText, Download, Eye, ChevronLeft, ChevronRight, RefreshCw, MoreHorizontal, Trash2, Loader2 } from 'lucide-react';
import { Button, Card, CardContent, CardHeader, CardTitle, Dropdown, Modal } from '../components/UI';
import { formatRelativeTime, formatDate, getErrorMessage } from '../utils/helpers';
import toast from 'react-hot-toast';

export function Reports() {
  const [reports, setReports] = useState<Report[]>([]);
  const [total, setTotal] = useState(0);
  const [page, setPage] = useState(1);
  const [pageSize] = useState(10);
  const [loading, setLoading] = useState(false);
  const [selectedReport, setSelectedReport] = useState<Report | null>(null);
  const [scanInfo, setScanInfo] = useState<Scan | null>(null);
  const [showDetails, setShowDetails] = useState(false);

  const fetchReports = async () => {
    setLoading(true);
    try {
      const res = await reportsApi.list({ page, page_size: pageSize });
      setReports(res.data.data?.items || []);
      setTotal(res.data.data?.total || 0);
    } catch (err: any) {
      toast.error(getErrorMessage(err, 'Failed to load reports'));
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => { fetchReports(); }, [page]);

  const downloadReport = async (report: Report) => {
    try {
      const blob = await reportsApi.download(report.id);
      const url = window.URL.createObjectURL(blob.data);
      const a = document.createElement('a');
      a.href = url;
      a.download = `compliance_report_scan_${report.scan_id}.pdf`;
      a.click();
      window.URL.revokeObjectURL(url);
    } catch {
      toast.error('Download failed');
    }
  };

  const viewReport = async (report: Report) => {
    setSelectedReport(report);
    try {
      const res = await scansApi.get(report.scan_id);
      setScanInfo(res.data.data);
      setShowDetails(true);
    } catch {
      toast.error('Failed to load scan info');
    }
  };

  const deleteReport = async (id: number) => {
    if (!confirm('Delete this report?')) return;
    try {
      await reportsApi.delete(id);
      toast.success('Report deleted');
      fetchReports();
    } catch (err: any) {
      toast.error(getErrorMessage(err, 'Delete failed'));
    }
  };

  return (
    <div className="space-y-6">
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
        <div>
          <h1 className="text-2xl font-bold text-gray-900">Reports</h1>
          <p className="text-gray-500">Download compliance reports for completed scans</p>
        </div>
        <Button variant="outline" onClick={fetchReports}>
          <RefreshCw className="w-4 h-4 mr-1" /> Refresh
        </Button>
      </div>

      {/* Table */}
      <Card>
        <CardContent className="p-0">
          <div className="overflow-x-auto">
            <table className="w-full text-sm">
              <thead>
                <tr className="bg-gray-50 border-b border-gray-200">
                  <th className="px-4 py-3 text-left font-medium text-gray-500">Scan</th>
                  <th className="px-4 py-3 text-left font-medium text-gray-500">Generated</th>
                  <th className="px-4 py-3 text-left font-medium text-gray-500">Generated By</th>
                  <th className="px-4 py-3 text-left font-medium text-gray-500">Actions</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-gray-200">
                {loading && (
                  <tr>
                    <td colSpan={4} className="px-4 py-8 text-center">
                      <div className="flex items-center justify-center gap-2">
                        <Loader2 className="w-5 h-5 animate-spin" />
                        <span className="text-gray-500">Loading...</span>
                      </div>
                    </td>
                  </tr>
                )}
                {!loading && reports.length === 0 && (
                  <tr>
                    <td colSpan={4} className="px-4 py-12 text-center">
                      <div className="flex flex-col items-center gap-3 text-gray-400">
                        <FileText className="w-12 h-12" />
                        <p>No reports generated yet</p>
                      </div>
                    </td>
                  </tr>
                )}
                {reports.map(report => (
                  <tr key={report.id} className="hover:bg-gray-50">
                    <td className="px-4 py-3">
                      <div className="font-medium text-gray-900">Scan #{report.scan_id}</div>
                      <div className="text-xs text-gray-500">Report ID: {report.id}</div>
                    </td>
                    <td className="px-4 py-3">
                      <div>{formatRelativeTime(report.created_at)}</div>
                      <div className="text-xs text-gray-500">{formatDate(report.created_at)}</div>
                    </td>
                    <td className="px-4 py-3">
                      {report.generated_by ? (
                        <span>User #{report.generated_by}</span>
                      ) : (
                        <span className="text-gray-400">System</span>
                      )}
                    </td>
                    <td className="px-4 py-3">
                      <Dropdown
                        trigger={<Button variant="ghost" size="sm"><MoreHorizontal className="w-4 h-4" /></Button>}
                        items={[
                          { label: 'View Details', onClick: () => viewReport(report), icon: <Eye className="w-4 h-4" /> },
                          { label: 'Download PDF', onClick: () => downloadReport(report), icon: <Download className="w-4 h-4" /> },
                          { label: 'Delete', onClick: () => deleteReport(report.id), icon: <Trash2 className="w-4 h-4" />, danger: true },
                        ]}
                        align="right"
                      />
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>

            {total > pageSize && (
              <div className="px-4 py-3 border-t border-gray-200 flex items-center justify-between">
                <p className="text-sm text-gray-500">
                  Showing {((page - 1) * pageSize) + 1} to {Math.min(page * pageSize, total)} of {total}
                </p>
                <div className="flex gap-2">
                  <Button variant="outline" size="sm" onClick={() => setPage(p => p - 1)} disabled={page === 1}>
                    <ChevronLeft className="w-4 h-4" />
                  </Button>
                  <Button variant="outline" size="sm" onClick={() => setPage(p => p + 1)} disabled={page * pageSize >= total}>
                    <ChevronRight className="w-4 h-4" />
                  </Button>
                </div>
              </div>
            )}
          </div>
        </CardContent>
      </Card>

      {/* Quick Generate */}
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <FileText className="w-5 h-5" />
            Generate New Report
          </CardTitle>
        </CardHeader>
        <CardContent>
          <p className="text-sm text-gray-500 mb-4">Select a completed scan to generate a compliance report PDF</p>
          <GenerateReportModal onClose={fetchReports} />
        </CardContent>
      </Card>

      {/* Report Details Modal */}
      <Modal
        isOpen={showDetails}
        onClose={() => setShowDetails(false)}
        title={`Report Details: Scan #${selectedReport?.scan_id}`}
        size="lg"
      >
        <div className="space-y-4">
          {scanInfo && (
            <>
              <div className="grid grid-cols-2 gap-4">
                <div className="p-3 bg-gray-50 rounded-lg">
                  <p className="text-sm text-gray-500">Scan File</p>
                  <p className="font-medium">{scanInfo.original_filename}</p>
                </div>
                <div className="p-3 bg-gray-50 rounded-lg">
                  <p className="text-sm text-gray-500">Scan Status</p>
                  <p className="font-medium capitalize">{scanInfo.status}</p>
                </div>
                <div className="p-3 bg-gray-50 rounded-lg">
                  <p className="text-sm text-gray-500">Verdict</p>
                  <p className="font-medium capitalize">{scanInfo.verdict ?? '—'}</p>
                </div>
                <div className="p-3 bg-gray-50 rounded-lg">
                  <p className="text-sm text-gray-500">Compliance Score</p>
                  <p className="font-medium">{scanInfo.compliance_score?.toFixed(1) ?? '—'}%</p>
                </div>
              </div>
              <div className="flex gap-2">
                <Button onClick={() => downloadReport(selectedReport!)}>
                  <Download className="w-4 h-4 mr-1" /> Download PDF
                </Button>
                <Button variant="outline" onClick={() => window.open(`/scan/${scanInfo.id}`, '_blank')}>
                  <Eye className="w-4 h-4 mr-1" /> View Scan
                </Button>
              </div>
            </>
          )}
        </div>
      </Modal>
    </div>
  );
}

// Separate component for generating reports
function GenerateReportModal({ onClose }: { onClose: () => void }) {
  const [scans, setScans] = useState<Scan[]>([]);
  const [loading] = useState(false);
  const [selectedScan, setSelectedScan] = useState<number | null>(null);
  const [generating, setGenerating] = useState(false);

  useEffect(() => {
    scansApi.list({ page_size: 50, status: 'completed' }).then(res => {
      setScans(res.data.data?.items || []);
    });
  }, []);

  const handleGenerate = async () => {
    if (!selectedScan) return;
    setGenerating(true);
    try {
      await reportsApi.generate(selectedScan);
      toast.success('Report generated successfully');
      setSelectedScan(null);
      onClose();
    } catch (err: any) {
      toast.error(getErrorMessage(err, 'Failed to generate'));
    } finally {
      setGenerating(false);
    }
  };

  return (
    <div className="flex flex-col sm:flex-row gap-4">
      <select
        value={selectedScan || ''}
        onChange={e => setSelectedScan(e.target.value ? Number(e.target.value) : null)}
        className="flex-1 px-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-primary-500"
        disabled={loading}
      >
        <option value="">Select a completed scan...</option>
        {scans.map(s => (
          <option key={s.id} value={s.id}>
            {s.original_filename} (Score: {s.compliance_score?.toFixed(1) ?? '—'}%)
          </option>
        ))}
      </select>
      <Button onClick={handleGenerate} disabled={!selectedScan || generating} loading={generating}>
        Generate Report
      </Button>
    </div>
  );
}